[tool.poetry]
name = "helproad74bot"
version = "1.0.0"
description = ""
authors = ["feechka"]

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
python-telegram-bot = "20.7"
openai = "1.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
